title: Mi Experiencia Python
description: > # this means to ignore newlines until "baseurl:"
  Este blog está dedicado al lenguaje de programación Python
  y tecnologías Web
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leomartinez2019.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
twitter_username: Pythonista100
# Build settings
markdown: kramdown
theme: jekyll-theme-architect
#gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
